import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { TableModule } from 'primeng/table';
import { InputTextModule } from 'primeng/inputtext';

export interface JutsuOtgItem {
  character: string;
  baseJ1: string;
  baseJ2: string;
  awkJ1: string;
  awkJ2: string;
  notes: string;
}

@Component({
  selector: 'app-jutsu-database',
  standalone: true,
  imports: [CommonModule, FormsModule, TableModule, InputTextModule],
  templateUrl: './jutsu-database.html',
  styleUrl: './jutsu-database.scss',
})
export class JutsuDatabase implements OnInit {
  searchValue: string = '';
  jutsuList: JutsuOtgItem[] = [];

  ngOnInit(): void {
    this.jutsuList = [
      { character: 'Ashura', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'YES', awkJ2: 'YES', notes: 'Nothing to note' },
      { character: 'Asuma', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Ay', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Boro', baseJ1: 'NO', baseJ2: 'YES', awkJ1: 'NO', awkJ2: 'YES', notes: 'Nothing to note' },
      { character: 'Borushiki', baseJ1: 'YES', baseJ2: 'NO', awkJ1: 'YES*', awkJ2: 'NO', notes: 'Awakening J1 from the air hits grounded' },
      { character: 'Boruto', baseJ1: 'YES', baseJ2: 'NO', awkJ1: 'YES', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Boruto (Karma)', baseJ1: 'YES', baseJ2: 'NO', awkJ1: 'YES', awkJ2: 'YES', notes: 'Nothing to note' },
      { character: 'Boruto CE', baseJ1: 'YES*', baseJ2: 'YES*', awkJ1: 'YES*', awkJ2: 'YES', notes: 'CE = Chunin Exam. Base J1 and Awakening J1 only hit grounded if used from the air' },
      { character: 'Boruto SNT', baseJ1: 'NO', baseJ2: 'YES*', awkJ1: 'NO', awkJ2: 'YES*', notes: 'J2 (2nd & 3rd input hits grounded) | SNT = Scientific Ninja Tool' },
      { character: 'Chiyo', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Choji (Boruto)', baseJ1: 'YES', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Choji PTS', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Choji Shippuden', baseJ1: 'YES', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Danzo', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Darui', baseJ1: 'NO', baseJ2: 'YES', awkJ1: 'NO', awkJ2: 'YES', notes: 'Nothing to note' },
      { character: 'Darui (Boruto)', baseJ1: 'NO', baseJ2: 'YES', awkJ1: 'NO', awkJ2: 'YES', notes: 'Nothing to note' },
      { character: 'Deidara', baseJ1: 'YES', baseJ2: 'YES', awkJ1: 'YES', awkJ2: 'YES', notes: '3rd input of Square Up Combo hits grounded & Left Awakening Action hits grounded' },
      { character: 'Delta', baseJ1: 'YES', baseJ2: 'NO', awkJ1: 'YES', awkJ2: 'NO', notes: 'Both Awakening Actions hit grounded (the explosion itself)' },
      { character: 'Fuu', baseJ1: 'YES', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'Both Awakening Actions hit grounded' },
      { character: 'Gaara PTS', baseJ1: 'NO', baseJ2: 'YES', awkJ1: 'NO', awkJ2: 'YES', notes: 'Nothing to note' },
      { character: 'Gaara (Boruto)', baseJ1: 'YES', baseJ2: 'YES', awkJ1: 'YES', awkJ2: 'YES', notes: 'Nothing to note' },
      { character: 'Gaara Shippuden', baseJ1: 'YES', baseJ2: 'YES', awkJ1: 'YES', awkJ2: 'YES', notes: 'Jinchuriki Gaara does not have any OTG tech in awakening' },
      { character: 'Guy (Night)', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Hagoromo', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Haku', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Han', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Hanabi', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Hanzo', baseJ1: 'YES', baseJ2: 'NO', awkJ1: 'YES', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Hashirama Alive', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'YES', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Hashirama Edo', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Hidan', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'Left Awakening Action hits grounded. Right Action when using hits grounded. Phantom Right action hits grounded.' },
      { character: 'Hinata (Boruto)', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Hinata PTS', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Hinata Shippuden', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Hiruzen', baseJ1: 'NO', baseJ2: 'YES', awkJ1: 'NO', awkJ2: 'YES', notes: 'Nothing to note' },
      { character: 'Indra', baseJ1: 'NO', baseJ2: 'YES', awkJ1: 'YES', awkJ2: 'YES', notes: 'Nothing to note' },
      { character: 'Ino (Boruto)', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Ino PTS', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Ino Shippuden', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Iruka', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Isshiki', baseJ1: 'YES', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Itachi', baseJ1: 'YES', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Jigen', baseJ1: 'NO', baseJ2: 'YES', awkJ1: 'YES', awkJ2: 'YES', notes: 'Nothing to note' },
      { character: 'Jiraiya', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Jirobo', baseJ1: 'NO', baseJ2: 'YES', awkJ1: 'YES', awkJ2: 'YES', notes: 'Nothing to note' },
      { character: 'Jugo', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Kabuto', baseJ1: 'NO', baseJ2: 'YES', awkJ1: 'NO', awkJ2: 'YES', notes: 'Nothing to note' },
      { character: 'Kabuto Hooded', baseJ1: 'NO', baseJ2: 'YES', awkJ1: 'NO', awkJ2: 'YES', notes: 'Both Awakening Actions hit grounded' },
      { character: 'Kabuto Sage Mode', baseJ1: 'NO', baseJ2: 'YES', awkJ1: 'NO', awkJ2: 'YES', notes: 'Left Awakening Action hits grounded | UC2 (Up Combo 2nd input) hits grounded' },
      { character: 'Kaguya', baseJ1: 'FIRE & SAND*', baseJ2: 'NO', awkJ1: 'FIRE & SAND*', awkJ2: 'NO', notes: 'Only on fire stage and sand stage does her J1 hit grounded' },
      { character: 'Kakashi (Kid)', baseJ1: 'NO', baseJ2: 'YES', awkJ1: 'YES', awkJ2: 'YES', notes: 'Nothing to note' },
      { character: 'Kakashi DMS', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'YES', notes: 'Nothing to note' },
      { character: 'Kakashi S3', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Kakuzu', baseJ1: 'YES', baseJ2: 'YES', awkJ1: 'YES', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Kankuro (Boruto)', baseJ1: 'YES', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Kankuro PTS', baseJ1: 'YES', baseJ2: 'NO', awkJ1: 'YES', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Kankuro Shippuden', baseJ1: 'YES', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Karin', baseJ1: 'NO', baseJ2: 'YES', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Kawaki', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Kawashiki', baseJ1: 'YES*', baseJ2: 'NO', awkJ1: 'YES', awkJ2: 'NO', notes: 'Charged Base J1 hits grounded | Both Awakening Actions hit grounded' },
      { character: 'Kiba (Boruto)', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Kiba PTS', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Kiba Shippuden', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Kidomaru', baseJ1: 'YES', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'Charged J1 also hits grounded' },
      { character: 'Killer Bee', baseJ1: 'NO', baseJ2: 'YES', awkJ1: 'NO', awkJ2: 'NO', notes: 'Both Awakening Actions hit grounded' },
      { character: 'Killer Bee Shark Skin', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'Both Awakening Actions hit grounded' },
      { character: 'Kimimaro', baseJ1: 'YES', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Kinshiki', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Kisame', baseJ1: 'NO', baseJ2: 'YES', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Koji', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Konan', baseJ1: 'YES', baseJ2: 'NO', awkJ1: 'YES', awkJ2: 'NO', notes: 'Both Awakening Actions hit grounded' },
      { character: 'Konohamaru', baseJ1: 'NO', baseJ2: 'YES', awkJ1: 'NO', awkJ2: 'YES', notes: 'Right Awakening Action hits grounded' },
      { character: 'Kurenai', baseJ1: 'YES', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'YES', notes: 'Nothing to note' },
      { character: 'Kushina', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Madara (Fan)', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Madara S3', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Madara SixPaths', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Masked Man', baseJ1: 'NO', baseJ2: 'YES', awkJ1: 'NO', awkJ2: 'YES', notes: 'Nothing to note' },
      { character: 'Mei', baseJ1: 'YES', baseJ2: 'YES', awkJ1: 'YES', awkJ2: 'YES', notes: 'Right Awakening Action hits grounded' },
      { character: 'Mifune', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'YES', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Minato Alive', baseJ1: 'NO', baseJ2: 'YES', awkJ1: 'NO', awkJ2: 'YES', notes: 'ic4 (intro combo 4th input) hits grounded' },
      { character: 'Minato Edo', baseJ1: 'NO', baseJ2: 'YES', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Mitsuki', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Mizukage (2nd)', baseJ1: 'YES', baseJ2: 'NO', awkJ1: 'YES', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Momoshiki', baseJ1: 'NO', baseJ2: 'YES', awkJ1: 'YES', awkJ2: 'YES', notes: 'Nothing to note' },
      { character: 'Mu (Tsuchikage 2nd)', baseJ1: 'NO', baseJ2: 'YES', awkJ1: 'NO', awkJ2: 'YES', notes: 'Nothing to note' },
      { character: 'Nagato', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Nanashi Uchiha', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'ic4 hits grounded' },
      { character: 'Naruto NTR', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'NTR = Nine Tail Rasengan Naruto' },
      { character: 'Naruto (Boruto)', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'YES', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Naruto Baryon Mode', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'YES', notes: 'Nothing to note' },
      { character: 'Naruto KLM', baseJ1: 'NO', baseJ2: 'YES', awkJ1: 'YES', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Naruto Mecha', baseJ1: 'NO', baseJ2: 'YES', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Naruto PTS', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Naruto Sage Mode', baseJ1: 'YES', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Naruto SixPaths', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Naruto SMR', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'SMR = Sage Art Massive Rasengan Barrage Naruto' },
      { character: 'Naruto TBB', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'YES', notes: 'Nothing to note' },
      { character: 'Naruto TL', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Neji', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Neji PTS', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Obito (Kid)', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Obito (War Mask)', baseJ1: 'NO', baseJ2: 'YES', awkJ1: 'NO', awkJ2: 'YES', notes: 'Nothing to note' },
      { character: 'Obito 10 Tails', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Obito No Mask (war)', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Obito Rampage', baseJ1: 'NO', baseJ2: 'YES', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Ohnoki', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Orochimaru', baseJ1: 'NO', baseJ2: 'YES', awkJ1: 'NO', awkJ2: 'YES', notes: 'Nothing to note' },
      { character: 'Pain', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Raikage (3rd)', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Rasa (4th Kazekage)', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'UC1 (Up Combo 1st input) hits grounded' },
      { character: 'Rin', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Rock Lee (Boruto)', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Rock Lee PTS', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Rock Lee Shippuden', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Roshi', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Sai', baseJ1: 'YES', baseJ2: 'NO', awkJ1: 'YES', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Sai (Boruto)', baseJ1: 'YES', baseJ2: 'NO', awkJ1: 'YES', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Sakon', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Sakura (Boruto)', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Sakura PTS', baseJ1: 'NO', baseJ2: 'YES', awkJ1: 'NO', awkJ2: 'YES', notes: 'Nothing to note' },
      { character: 'Sakura Shippuden', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Sarada BT', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'BT = Blade Trap Sarada' },
      { character: 'Sarada COTB', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'COTB = Chidori Sarada' },
      { character: 'Sasori', baseJ1: 'YES', baseJ2: 'YES', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Sasuke (Boruto)', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Sasuke 5KS', baseJ1: 'NO', baseJ2: 'YES', awkJ1: 'YES', awkJ2: 'YES', notes: 'Nothing to note' },
      { character: 'Sasuke EMS', baseJ1: 'NO', baseJ2: 'YES', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Sasuke Kirin', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'YES', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Sasuke PTS', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'Both PTS Sasukes have no OTG tech' },
      { character: 'Sasuke Rinne', baseJ1: 'NO', baseJ2: 'YES', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Sasuke SK', baseJ1: 'YES*', baseJ2: 'YES*', awkJ1: 'NO', awkJ2: 'NO', notes: 'SK = Supporting Kage | J2 charged hits grounded | Knocked Down bodies can be teleported' },
      { character: 'Sasuke Taka', baseJ1: 'NO', baseJ2: 'YES', awkJ1: 'NO', awkJ2: 'YES', notes: 'Nothing to note' },
      { character: 'Sasuke TL', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Shikamaru (Boruto)', baseJ1: 'YES', baseJ2: 'NO', awkJ1: 'YES', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Shikamaru PTS', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Shikamaru Shippuden', baseJ1: 'YES', baseJ2: 'NO', awkJ1: 'YES', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Shino (Boruto)', baseJ1: 'YES', baseJ2: 'YES', awkJ1: 'YES', awkJ2: 'YES', notes: 'Nothing to note' },
      { character: 'Shino PTS', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Shino Shippuden', baseJ1: 'YES', baseJ2: 'YES', awkJ1: 'YES', awkJ2: 'YES', notes: 'Nothing to note' },
      { character: 'Shisui', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Suigetsu', baseJ1: 'YES', baseJ2: 'NO', awkJ1: 'YES', awkJ2: 'NO', notes: 'Right Awakening Action hits grounded' },
      { character: 'Tayuya', baseJ1: 'NO', baseJ2: 'YES', awkJ1: 'NO', awkJ2: 'NO', notes: 'Rage Ogre Club Doki Hits grounded' },
      { character: 'Temari (Boruto)', baseJ1: 'YES', baseJ2: 'YES', awkJ1: 'NO', awkJ2: 'YES', notes: 'Air & Grounded Square combo hits grounded' },
      { character: 'Temari PTS', baseJ1: 'YES', baseJ2: 'YES', awkJ1: 'YES', awkJ2: 'YES', notes: 'Nothing to note' },
      { character: 'Temari Shippuden', baseJ1: 'YES', baseJ2: 'YES', awkJ1: 'NO', awkJ2: 'YES', notes: 'Air & Grounded Square combo hits grounded' },
      { character: 'Tenten (Boruto)', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'Awakening Grounded Square combo hits grounded' },
      { character: 'Tenten PTS', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Tenten Shippuden', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'Awakening Grounded Square combo hits grounded' },
      { character: 'Tobi', baseJ1: 'NO', baseJ2: 'YES', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Tobirama', baseJ1: 'YES', baseJ2: 'NO', awkJ1: 'YES', awkJ2: 'NO', notes: 'Both Awakening Actions hit grounded' },
      { character: 'Tsunade', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Utakata', baseJ1: 'YES', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'YES', notes: 'Both Awakening Actions hit grounded' },
      { character: 'Yagura', baseJ1: 'YES', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' },
      { character: 'Yamato', baseJ1: 'NO', baseJ2: 'YES', awkJ1: 'NO', awkJ2: 'YES', notes: 'Nothing to note' },
      { character: 'Yugito', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'YES', notes: 'Nothing to note' },
      { character: 'Zabuza', baseJ1: 'NO', baseJ2: 'NO', awkJ1: 'NO', awkJ2: 'NO', notes: 'Nothing to note' }
    ];
  }

  isYes(val: string): boolean {
    return val.toUpperCase().includes('YES');
  }
}